### ISSUE TITLE
[内容有误] 二项堆的插入操作复杂度是否为 O(1)

### ISSUE THREAD

**Issue by untitledunrevised** [OI-wiki/OI-wiki#5130]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/heap/#%E5%A0%86%E7%9A%84%E5%88%86%E7%B1%BB

### 我发现页面有这样的问题

从大多数资料来看，二项堆的插入操作时间复杂度应为 $O(\log n)$。是误打还是确实存在一种 $O(1)$ 的做法？

**Comment by tripleInt** [comment]
确实错误了，该操作复杂度确实为 log 的，目前没有常数做法。发自我的iPhone------------------ 原始邮件 ------------------发件人: Untitled_unrevised  ***@***.***>发送时间: 2023年9月7日 20:18收件人: OI-wiki/OI-wiki ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [OI-wiki/OI-wiki] [内容有误] 二项堆的插入操作复杂度是否为 O(1) (Issue #5130)
请选择：

 我正在着手修复这个问题

我正在访问这个页面
https://oi-wiki.org/ds/heap/#%E5%A0%86%E7%9A%84%E5%88%86%E7%B1%BB
我发现页面有这样的问题
从大多数资料来看，二项堆的插入操作时间复杂度应为 $O(\log n)$。是误打还是确实存在一种 $O(1)$ 的做法？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OI-wiki/OI-wiki/issues/5130",
"url": "https://github.com/OI-wiki/OI-wiki/issues/5130",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by HeRaNO** [comment]
https://en.wikipedia.org/wiki/Binomial_heap#Insert 这里的表达是 $O(1)$ 是一个均摊复杂度，在表格注释里也有说明，单次插入是 $O(\log n)$ 的。

但是表格里 find-min 的复杂度应该也是有问题的，wikipedia 上是 $O(1)$，但是 OI Wiki 上是 $O(\log n)$.
